extends SceneTree
const Impact = preload("res://scripts/combat_impact_rules.gd")
const Countermeasures = preload("res://scripts/countermeasure_rules.gd")
const ProjectileRules = preload("res://scripts/projectile_rules.gd")
var failures: Array[String] = []
func _initialize() -> void:
	check(ProjectileRules.missile_in_acquisition_envelope(Vector2(0,0),Vector2(0,430)), "Missile acquisition should cover the authored warning envelope")
	check(ProjectileRules.enemy_has_firing_solution(Vector2(200,100),Vector2(220,260),"cannon","air"), "forward aircraft guns should fire on a downrange target")
	check(not ProjectileRules.enemy_has_firing_solution(Vector2(200,260),Vector2(220,100),"cannon","air"), "fixed aircraft guns should not fire backward after overshooting")
	check(ProjectileRules.uses_fixed_aircraft_gun("air","aggressive_weave","twin_burst"), "fighter-class weave contacts should use fixed forward guns")
	check(not ProjectileRules.uses_fixed_aircraft_gun("air","bomber_run","cannon"), "bomber defensive cannon should retain a traversing mount")
	check(not ProjectileRules.uses_fixed_aircraft_gun("ground","road_column","twin_burst"), "surface mounts should retain turret fire")
	check(ProjectileRules.fixed_aircraft_has_boresight(Vector2(200,100),Vector2(220,220),20.0,180.0), "banking fighter should fire when its projected gun line crosses the target")
	check(not ProjectileRules.fixed_aircraft_has_boresight(Vector2(200,100),Vector2(320,220),0.0,180.0), "fixed gun should hold fire when the target is outside its boresight")
	var boresight_velocity := ProjectileRules.fixed_aircraft_shot_velocity(-48.0,200.0)
	check(boresight_velocity.x < 0.0 and boresight_velocity.y > 0.0 and is_equal_approx(boresight_velocity.length(),200.0), "fixed gun rounds should inherit the aircraft heading at authored projectile speed")
	var twin_origins := ProjectileRules.twin_gun_origins(Vector2(200,100),Vector2.DOWN*180.0)
	check(twin_origins.size() == 2 and is_equal_approx(twin_origins[0].distance_to(twin_origins[1]),8.0), "twin cannon fire should originate from two physical stations")
	check(is_equal_approx(twin_origins[0].y,twin_origins[1].y) and twin_origins[0].x != twin_origins[1].x, "forward twin cannons should fire parallel rounds across the airframe")
	check(ProjectileRules.enemy_has_firing_solution(Vector2(200,170),Vector2(260,120),"side_burst","air"), "door guns should retain their authored broad beam arc")
	check(not ProjectileRules.enemy_has_firing_solution(Vector2(200,240),Vector2(200,120),"deck_gun","sea"), "surface mounts should not fire through their own hull after the player passes")
	check(not ProjectileRules.enemy_has_firing_solution(Vector2(200,100),Vector2(200,560),"cannon","ground"), "surface weapons should respect their credible engagement range")
	check(not ProjectileRules.missile_launch_has_warning_time(Vector2(0,0),Vector2(0,144),161.04), "Ace missiles must not launch with less than 0.9 seconds of reaction time")
	check(ProjectileRules.missile_launch_has_warning_time(Vector2(0,0),Vector2(0,145),161.04), "Ace missiles should launch once the 0.9-second reaction window is available")
	check(ProjectileRules.enemy_missile_capacity("air") == 2, "Aircraft should carry one lethal two-missile salvo")
	check(ProjectileRules.enemy_missile_capacity("ground") == 4, "SAM sites should carry two lethal salvos")
	check(ProjectileRules.enemy_missile_capacity("sea") == 6, "Naval launchers should carry three lethal salvos")
	check(ProjectileRules.enemy_missile_capacity("air", true) == 8, "Boss main batteries should carry four normal salvos")
	check(ProjectileRules.missile_salvo_available(2) and not ProjectileRules.missile_salvo_available(1), "A twin launch must require two remaining rounds")
	check(ProjectileRules.missile_launch_authorized(0.0, 3), "A coordinated battery should authorize a warned salvo below the active threat cap")
	check(not ProjectileRules.missile_launch_authorized(0.2, 0), "Missile batteries should respect the shared engagement interval")
	check(not ProjectileRules.missile_launch_authorized(0.0, ProjectileRules.MAX_ACTIVE_GUIDED_MISSILES), "Missile batteries should hold fire at the active guided-threat cap")
	check(Impact.projectile_class("missile") == Impact.DIRECT_WARHEAD, "Missiles need direct-warhead impacts")
	check(Impact.guidance_class("missile") == Impact.HEAT_SEEKING, "Current Sidewinder-like missiles need heat-seeking guidance")
	var direct := Impact.apply(160,140,13,Impact.DIRECT_WARHEAD,0.65)
	check(direct.hull == 0 and direct.shield == 0 and direct.catastrophic, "A successful direct warhead must destroy even an upgraded craft")
	var collision := Impact.apply(160,140,18,Impact.AIRFRAME_COLLISION,0.65)
	check(collision.hull == 0 and collision.shield == 0 and collision.catastrophic, "An airframe collision must be catastrophic despite shield or hull upgrades")
	var state := {"hull":100,"shield":100}
	for i in 2: state = Impact.apply(state.hull,state.shield,8,Impact.AUTOCANNON,1.0)
	check(state.hull == 44 and state.shield == 80, "Two autocannon hits should leave basic airframe critical but flying")
	state = Impact.apply(state.hull,state.shield,8,Impact.AUTOCANNON,1.0)
	state = Impact.apply(state.hull,state.shield,8,Impact.AUTOCANNON,1.0)
	check(state.hull == 0, "Four basic autocannon hits must destroy the craft")
	var heavy := Impact.apply(100,100,12,Impact.HEAVY_CANNON,1.0)
	heavy = Impact.apply(heavy.hull,heavy.shield,12,Impact.HEAVY_CANNON,1.0)
	heavy = Impact.apply(heavy.hull,heavy.shield,12,Impact.HEAVY_CANNON,1.0)
	check(heavy.hull == 0, "Three heavy cannon hits must destroy the basic craft")
	var fragment := Impact.apply(100,20,9,Impact.FRAGMENT,1.0)
	check(fragment.hull == 100 and fragment.shield == 11, "Fragments should remain recoverable shield damage")
	var threats: Array = [
		{"position":Vector2(100,100),"velocity":Vector2.DOWN*180,"homing":true,"guidance_class":"heat_seeking","homing_speed":180.0},
		{"position":Vector2(104,100),"velocity":Vector2.DOWN*180,"homing":true,"guidance_class":"radar","homing_speed":180.0},
	]
	check(Countermeasures.divert_missiles(threats,Vector2(120,220),Vector2(154,294)) == 1, "Flares must divert heat seekers only")
	check(threats[0].countermeasure_decoyed and threats[1].homing, "Radar guidance must ignore heat flares")
	var guided := {"position":Vector2(100,100),"velocity":Vector2.RIGHT*100,"homing":true,"homing_speed":100.0,"turn_rate":2.0,"life":2.0}
	var advanced := preload("res://scripts/projectile_rules.gd").advance_enemy_shot(guided,Vector2(100,200),0.25)
	check(Vector2(advanced.velocity).y > 0.0 and float(advanced.life) == 1.75, "Live seeker must turn toward target and consume finite lifetime")
	var main_source := FileAccess.get_file_as_string("res://scripts/main.gd")
	check(main_source.contains("_apply_projectile_impact(shot)") and main_source.contains('"DIRECT WARHEAD IMPACT // AIRFRAME LOST"'), "Runtime projectile collision must use classified impact outcome")
	check(main_source.contains("CombatImpactRules.AIRFRAME_COLLISION") and main_source.contains('"AIRFRAME COLLISION // STRUCTURAL LOSS"') and main_source.contains("_register_destroy(collided_enemy)"), "Runtime craft collision should destroy both airframes and register hostile breakup")
	check(main_source.contains('if not boss_contact and contact_category != "air"') and main_source.contains("continue"), "ground and naval targets should never become airborne collision hazards")
	if failures.is_empty(): print("HYPERSONIC combat impact self-test passed: catastrophic warheads, penetrating cannon, recoverable fragments and heat-only flares.")
	else:
		for failure in failures: push_error(failure)
	quit(0 if failures.is_empty() else 1)
func check(value: bool, message: String) -> void:
	if not value: failures.append(message)
