extends SceneTree

const SaveRecoveryRules = preload("res://scripts/save_recovery_rules.gd")

var failures: Array[String] = []

func _initialize() -> void:
	var valid := JSON.stringify({"version":12,"credits":100,"mission_index":1,"mission_id":"m02_refinery_run","generator_index":2,"airframe_index":3,"service_hull":133,"service_shield":118,"support_selected":2,"support_unlocked":3,"campaign_completed":true,"campaign_completions":2,"completed_difficulties":["combat","ace"],"discovered_secret_ids":["m01_coastal_intercept:hidden_ace"],"mode_records":{"arcade_assault":{"attempts":2,"clears":1,"best_route":12,"route_total":12,"best_score":82000,"cleared":true}},"branch_decisions":{"s1_breakwater_crisis":"furnace"},"intelligence_unlocked_ids":["vx94","atlas_tanker"],"completed_secret_mission_ids":["sm01_black_wake"],"career_statistics":{"sorties_attempted":8,"sorties_cleared":7,"shots_fired":940,"shots_hit":702,"targets_destroyed":318,"damage_taken":146,"secrets_discovered":3,"credits_earned":18400,"best_score":82000,"best_accuracy_per_mille":812}})
	var v11 := JSON.stringify({"version":11,"credits":100,"mission_index":1,"mission_id":"m02_refinery_run","completed_secret_mission_ids":["sm01_black_wake"]})
	var v10 := JSON.stringify({"version":10,"credits":100,"mission_index":1,"mission_id":"m02_refinery_run","intelligence_unlocked_ids":["vx94"]})
	var v9 := JSON.stringify({"version":9,"credits":100,"mission_index":1,"mission_id":"m02_refinery_run","branch_decisions":{"s1_breakwater_crisis":"furnace"}})
	var v8 := JSON.stringify({"version":8,"credits":100,"mission_index":1,"mission_id":"m02_refinery_run","campaign_completed":true,"discovered_secret_ids":["m01_coastal_intercept:hidden_ace"]})
	var v7 := JSON.stringify({"version":7,"credits":99,"mission_index":1,"mission_id":"m02_refinery_run","generator_index":2,"airframe_index":3,"service_hull":132,"service_shield":117,"support_selected":2,"support_unlocked":3,"campaign_completed":true,"campaign_completions":1,"completed_difficulties":["combat"]})
	var v6 := JSON.stringify({"version":6,"credits":98,"mission_index":1,"mission_id":"m02_refinery_run","generator_index":2,"airframe_index":3,"service_hull":130,"service_shield":115,"support_selected":2,"support_unlocked":3})
	var v5 := JSON.stringify({"version":5,"credits":95,"mission_index":6,"generator_index":2,"airframe_index":2,"service_hull":100,"service_shield":90,"support_selected":1,"support_unlocked":2})
	var v4 := JSON.stringify({"version":4,"credits":90,"mission_index":1,"generator_index":2,"service_hull":83,"service_shield":64,"support_selected":2,"support_unlocked":3})
	var v3 := JSON.stringify({"version":3,"credits":80,"mission_index":1,"generator_index":1,"service_hull":87,"service_shield":68})
	var v2 := JSON.stringify({"version":2,"credits":50,"mission_index":0,"service_hull":90,"service_shield":75})
	var legacy := JSON.stringify({"version":1,"credits":25,"mission_index":0})
	var unsupported := JSON.stringify({"version":99,"credits":999})
	var corrupt := "{not json"
	var parsed := SaveRecoveryRules.parse_supported_json(valid, 1, 12)
	_expect(int(parsed.get("credits", 0)) == 100 and int(parsed.get("airframe_index", -1)) == 3, "supported v12 JSON should preserve airframe tier")
	_expect(int(parsed.get("support_selected", -1)) == 2 and int(parsed.get("support_unlocked", -1)) == 3, "supported v7 JSON should preserve support loadout")
	_expect(bool(parsed.get("campaign_completed", false)) and int(parsed.get("campaign_completions", 0)) == 2, "supported v7 JSON should preserve campaign clear history")
	_expect(parsed.get("completed_difficulties", []).size() == 2, "supported v7 JSON should preserve difficulty clear records")
	_expect(parsed.get("discovered_secret_ids", []).size() == 1 and parsed.get("mode_records", {}).has("arcade_assault"), "supported v8 JSON should preserve secret and mode history")
	_expect(parsed.get("branch_decisions", {}).get("s1_breakwater_crisis", "") == "furnace", "supported v9 JSON should preserve stable branch decisions")
	_expect(parsed.get("intelligence_unlocked_ids", []).size() == 2, "supported v10 JSON should preserve intelligence unlocks")
	_expect(parsed.get("completed_secret_mission_ids", []).size() == 1, "supported v11 JSON should preserve secret-sortie clears")
	_expect(parsed.get("career_statistics", {}).get("targets_destroyed", 0) == 318, "supported v12 JSON should preserve career telemetry")
	_expect(SaveRecoveryRules.parse_supported_json(unsupported, 1, 12).is_empty(), "unsupported save version should be rejected")
	_expect(SaveRecoveryRules.parse_supported_json(corrupt, 1, 12).is_empty(), "corrupt JSON should be rejected")
	_expect(str(parsed.get("mission_id", "")) == "m02_refinery_run", "v12 save should retain stable mission identity")
	_expect(not SaveRecoveryRules.parse_supported_json(v11, 1, 12).is_empty(), "v11 saves should remain migration-compatible")
	_expect(not SaveRecoveryRules.parse_supported_json(v10, 1, 12).is_empty(), "v10 saves should remain migration-compatible")
	_expect(not SaveRecoveryRules.parse_supported_json(v9, 1, 12).is_empty(), "v9 saves should remain migration-compatible")
	_expect(not SaveRecoveryRules.parse_supported_json(v8, 1, 12).is_empty(), "v8 saves should remain migration-compatible")
	_expect(not SaveRecoveryRules.parse_supported_json(v7, 1, 12).is_empty(), "v7 saves should remain migration-compatible")
	_expect(not SaveRecoveryRules.parse_supported_json(v6, 1, 12).is_empty(), "v6 saves should remain migration-compatible")
	var primary := SaveRecoveryRules.choose_primary_or_backup(valid, v11, 1, 12)
	_expect(str(primary.get("source", "")) == "primary" and int(primary.get("data", {}).get("airframe_index", -1)) == 3, "valid v12 primary should win over v11 backup")
	var backup_v5 := SaveRecoveryRules.choose_primary_or_backup(corrupt, v5, 1, 12)
	_expect(str(backup_v5.get("source", "")) == "backup" and int(backup_v5.get("data", {}).get("mission_index", -1)) == 6, "v5 index save should remain available for stable-ID migration")
	var backup_v4 := SaveRecoveryRules.choose_primary_or_backup(corrupt, v4, 1, 12)
	_expect(str(backup_v4.get("source", "")) == "backup" and int(backup_v4.get("data", {}).get("credits", 0)) == 90, "corrupt primary should recover from supported v4 backup")
	var backup_v3 := SaveRecoveryRules.choose_primary_or_backup(corrupt, v3, 1, 12)
	_expect(str(backup_v3.get("source", "")) == "backup" and int(backup_v3.get("data", {}).get("credits", 0)) == 80, "v3 backup should remain migration-compatible")
	var backup_v2 := SaveRecoveryRules.choose_primary_or_backup(corrupt, v2, 1, 12)
	_expect(str(backup_v2.get("source", "")) == "backup" and int(backup_v2.get("data", {}).get("credits", 0)) == 50, "v2 backup should remain migration-compatible")
	var legacy_choice := SaveRecoveryRules.choose_primary_or_backup(corrupt, legacy, 1, 12)
	_expect(str(legacy_choice.get("source", "")) == "backup", "legacy v1 backup should remain migration-compatible")
	var none := SaveRecoveryRules.choose_primary_or_backup(corrupt, unsupported, 1, 12)
	_expect(str(none.get("source", "")) == "none" and none.get("data", {}).is_empty(), "invalid primary and backup should produce no restore state")
	var save_file := FileAccess.open("res://scripts/campaign_save.gd", FileAccess.READ)
	_expect(save_file != null, "campaign_save.gd should be readable for v9 schema checks")
	if save_file != null:
		var source := save_file.get_as_text()
		_expect(source.contains('"mission_id"') and source.contains("LEGACY_V5_MISSION_IDS"), "v7 save should persist mission IDs and map legacy mission indices")
		_expect(source.contains('"generator_index"') and source.contains('"service_hull"') and source.contains('"service_shield"'), "v7 snapshot should retain generator and serviced durability state")
		_expect(source.contains('"airframe_index"'), "v7 snapshot should persist VX-94 airframe tier")
		_expect(source.contains('SAVE_VERSION := 12') and source.contains('"support_selected"') and source.contains('"support_unlocked"'), "v12 snapshot should include support selection/unlock state")
		_expect(source.contains('"campaign_completed"') and source.contains('"completed_difficulties"') and source.contains("func save_now"), "v7 snapshot should persist campaign completion immediately")
		_expect(source.contains('"discovered_secret_ids"') and source.contains('"mode_records"') and source.contains("func _mode_records"), "v8 snapshot should persist sanitized secret and alternate-mode history")
		_expect(source.contains('"branch_decisions"') and source.contains("func _string_dictionary"), "v9 snapshot should persist sanitized branch decisions")
		_expect(source.contains('"intelligence_unlocked_ids"'), "v10 snapshot should persist intelligence database unlocks")
		_expect(source.contains('"completed_secret_mission_ids"'), "v11 snapshot should persist secret-sortie clear history")
		_expect(source.contains('"career_statistics"') and source.contains("func _career_statistics"), "v12 snapshot should persist sanitized career telemetry")
		_expect(source.contains("restore_airframe_state"), "v7 restore should restore airframe through public API")
		_expect(source.contains("restore_support_state"), "v7 restore should use public support restore API")
		_expect(source.contains("if _capture_mode():"), "deterministic visual captures must not restore or mutate campaign saves")
	if failures.is_empty():
		print("Strike Wing save recovery self-test passed.")
		quit(0)
		return
	for failure in failures:
		push_error(failure)
	quit(1)

func _expect(condition: bool, message: String) -> void:
	if not condition:
		failures.append(message)
